[tools]
node = "latest"
deno = "latest"
bun = "latest"
uv = "latest"
python = "latest"
usage = "latest"
ghq = "latest"
fzf = "latest"
fd = "10.3.0"
bat = "0.26.0"
ripgrep = "latest"
pnpm = "10.9.0"
yarn = "latest"
"pipx:tldr" = "latest"
"npm:@devcontainers/cli" = "latest"
"ubi:duckdb/duckdb" = "latest"

[settings]
experimental = true

[settings.pipx]
uvx = true
